name: Deploy Shiny Apps

on:
  push:
    branches:
      - auto-deploy-gallery

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install rsconnect
        run: pip install rsconnect-python

      - name: Deploy Shiny Apps
        run: |
          # Loop through the contents of the examples folder
          for app_path in examples/*; do
            if [ -d "$app_path" ]; then
              rsconnect deploy shiny $app_path -A gallery -T $TOKEN -S $SECRET -N
            fi
          done
        env:
          TOKEN: ${{secrets.SHINYAPPS_DEPLOY_TOKEN}}
          SECRET: ${{secrets.SHINYAPPS_DEPLOY_SECRET}}
